"""Add workspace sync_mode and desktop_instances table

Revision ID: 5af908451e83
Revises: 77ac0a5d841f
Create Date: 2026-04-05 04:01:26.457268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5af908451e83'
down_revision: Union[str, Sequence[str], None] = '77ac0a5d841f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sync_mode', sa.Enum('CLOUD', 'LOCAL', 'HYBRID', name='syncmode'), server_default='CLOUD', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.drop_column('sync_mode')

    # ### end Alembic commands ###
