"""add_media_columns

Revision ID: 66c9856bf81a
Revises: 5af908451e83
Create Date: 2026-06-23 00:27:01.489413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66c9856bf81a'
down_revision: Union[str, Sequence[str], None] = '5af908451e83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_id', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('media_type', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('media_url', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('media_url')
        batch_op.drop_column('media_type')
        batch_op.drop_column('media_id')

    # ### end Alembic commands ###
