"""phase5_templates

Revision ID: 77ac0a5d841f
Revises: 2c213583a4e0
Create Date: 2026-04-05 03:44:59.766219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77ac0a5d841f'
down_revision: Union[str, Sequence[str], None] = '2c213583a4e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('templates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('components_json', sa.JSON(), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('meta_account_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['meta_account_id'], ['meta_accounts.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_templates_meta_account_id'), ['meta_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_templates_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_templates_workspace_id'), ['workspace_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_templates_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_templates_name'))
        batch_op.drop_index(batch_op.f('ix_templates_meta_account_id'))

    op.drop_table('templates')
    # ### end Alembic commands ###
