"""phase3_outbound_and_lifecycle

Revision ID: c47c2a6fb09e
Revises: c6be37db20c1
Create Date: 2026-04-05 03:24:10.649812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c47c2a6fb09e'
down_revision: Union[str, Sequence[str], None] = 'c6be37db20c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Pre-populate NULL audit fields to avoid IntegrityErrors in SQLite batch mode
    op.execute("UPDATE messages SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL")
    op.execute("UPDATE messages SET updated_at = CURRENT_TIMESTAMP WHERE updated_at IS NULL")
    op.execute("UPDATE workspaces SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL")
    op.execute("UPDATE workspaces SET updated_at = CURRENT_TIMESTAMP WHERE updated_at IS NULL")
    op.execute("UPDATE users SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL")
    op.execute("UPDATE users SET updated_at = CURRENT_TIMESTAMP WHERE updated_at IS NULL")
    op.execute("UPDATE contacts SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL")
    op.execute("UPDATE contacts SET updated_at = CURRENT_TIMESTAMP WHERE updated_at IS NULL")
    op.execute("UPDATE conversations SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL")
    op.execute("UPDATE conversations SET updated_at = CURRENT_TIMESTAMP WHERE updated_at IS NULL")
    op.execute("UPDATE contracts SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL")
    op.execute("UPDATE contracts SET updated_at = CURRENT_TIMESTAMP WHERE updated_at IS NULL")
    op.execute("UPDATE labels SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL")
    
    # ### commands auto generated by Alembic - please adjust! ###
    # Redundant create_table for auto_reply_rules removed (already exists from previous revision)
    pass
    op.drop_table('_alembic_tmp_cloud_messages')
    with op.batch_alter_table('cloud_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.alter_column('conversation_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.alter_column('contact_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.alter_column('direction',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               nullable=False,
               existing_server_default=sa.text("'OUTBOUND'"))
        batch_op.alter_column('channel',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               nullable=False,
               existing_server_default=sa.text("'LOCAL'"))
        batch_op.alter_column('external_message_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_cloud_messages_id'))
        batch_op.create_index(batch_op.f('ix_cloud_messages_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cloud_messages_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cloud_messages_external_message_id'), ['external_message_id'], unique=False)

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_conversations_updated_at'))

    with op.batch_alter_table('labels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=32), server_default=sa.text("'PENDING'"), nullable=False))
        batch_op.add_column(sa.Column('provider_error_code', sa.String(length=64), nullable=True))
        batch_op.alter_column('conversation_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.alter_column('contact_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.alter_column('direction',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               nullable=False,
               existing_server_default=sa.text("'OUTBOUND'"))
        batch_op.alter_column('channel',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               nullable=False,
               existing_server_default=sa.text("'LOCAL'"))
        batch_op.alter_column('external_message_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_messages_created_at'))
        batch_op.create_index(batch_op.f('ix_messages_channel'), ['channel'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_direction'), ['direction'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_external_message_id'), ['external_message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_is_starred'), ['is_starred'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_sender_id'), ['sender_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_foreign_key('fk_messages_contact_id', 'contacts', ['contact_id'], ['id'])
        batch_op.create_foreign_key('fk_messages_conversation_id', 'conversations', ['conversation_id'], ['id'])

    with op.batch_alter_table('meta_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('workspace_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('workspace_members', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('meta_accounts', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_messages_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_messages_status'))
        batch_op.drop_index(batch_op.f('ix_messages_sender_id'))
        batch_op.drop_index(batch_op.f('ix_messages_parent_id'))
        batch_op.drop_index(batch_op.f('ix_messages_is_starred'))
        batch_op.drop_index(batch_op.f('ix_messages_external_message_id'))
        batch_op.drop_index(batch_op.f('ix_messages_direction'))
        batch_op.drop_index(batch_op.f('ix_messages_conversation_id'))
        batch_op.drop_index(batch_op.f('ix_messages_contact_id'))
        batch_op.drop_index(batch_op.f('ix_messages_channel'))
        batch_op.create_index(batch_op.f('ix_messages_created_at'), ['created_at'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('external_message_id',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('channel',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'LOCAL'"))
        batch_op.alter_column('direction',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'OUTBOUND'"))
        batch_op.alter_column('contact_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('conversation_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('provider_error_code')
        batch_op.drop_column('status')

    with op.batch_alter_table('labels', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_updated_at'), ['updated_at'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('cloud_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cloud_messages_external_message_id'))
        batch_op.drop_index(batch_op.f('ix_cloud_messages_conversation_id'))
        batch_op.drop_index(batch_op.f('ix_cloud_messages_contact_id'))
        batch_op.create_index(batch_op.f('ix_cloud_messages_id'), ['id'], unique=False)
        batch_op.alter_column('external_message_id',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('channel',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'LOCAL'"))
        batch_op.alter_column('direction',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'OUTBOUND'"))
        batch_op.alter_column('contact_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('conversation_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    op.create_table('_alembic_tmp_cloud_messages',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('sender_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('parent_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('attachment_path', sa.VARCHAR(length=512), nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=True),
    sa.Column('conversation_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('contact_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('direction', sa.VARCHAR(length=32), server_default=sa.text("'OUTBOUND'"), nullable=False),
    sa.Column('channel', sa.VARCHAR(length=32), server_default=sa.text("'LOCAL'"), nullable=False),
    sa.Column('external_message_id', sa.VARCHAR(length=128), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('auto_reply_rules')
    # ### end Alembic commands ###
